### ISSUE TITLE
Error: getaddrinfo ENOTFOUND www.www.thesaurus.com www.www.thesaurus.com:443

### ISSUE THREAD

**Issue by y12uc231** [mhinz/node-thesaurus-com#3]
hey, my node version is v11.4.0, and I am getting the following error for "tcom never".

/usr/local/lib/node_modules/thesaurus-com/node_modules/sync-request/index.js:37
    throw new Error(response.error.message || response.error || response);
    ^

Error: getaddrinfo ENOTFOUND www.www.thesaurus.com www.www.thesaurus.com:443
    at doRequest (/usr/local/lib/node_modules/thesaurus-com/node_modules/sync-request/index.js:37:11)
    at Object.search (/usr/local/lib/node_modules/thesaurus-com/index.js:6:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/thesaurus-com/tcom.js:37:20)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)

**Comment by mhinz** [comment]
Fixed by switching to HTTPS. Thanks! ✨
